version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - broker
  broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
